import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowRight, CheckCircle2, ClipboardList, FileText, Plus, Search, ShieldCheck, Upload, Wrench } from "lucide-react";
import { Link, useLocation } from "wouter";
import SiteHeader from "@/components/SiteHeader";
import ProductCard from "@/components/ProductCard";
import { categories, featuredCategoryNames, findProducts, getCategoryCardImage, products } from "@/lib/catalogue";
import { useRequirement } from "@/components/RequirementProvider";
import { business } from "@/lib/business";
import { MobileActionBar } from "@/components/MobileActionBar";
import { MotionReveal } from "@/components/Motion";

const heroImage = "/manus-storage/mas-hero-industrial-supply_d41860d6.jpg";
const logoUrl = "/manus-storage/logo.png";

export default function Home() {
  const [search, setSearch] = useState("");
  const [, navigate] = useLocation();
  const { add, setOpen, setQuoteOpen, items } = useRequirement();
  const matches = useMemo(() => search.trim() ? findProducts(search).slice(0, 5) : [], [search]);
  const featured = products.filter((item) => ["Safety Helmet", "Safety Gloves", "Angle Grinder Machines", "Drill Machines", "MS Bolt Nuts", "Anchor Bolts"].includes(item.name));
  const curated = categories.filter((item) => featuredCategoryNames.includes(item.category));

  const submitFinder = (event: React.FormEvent) => {
    event.preventDefault();
    navigate(`/catalogue${search ? `?q=${encodeURIComponent(search)}` : ""}`);
  };

  return <div className="min-h-screen overflow-x-hidden bg-[#f8fafc] text-slate-950"><SiteHeader />
    <main>
      <section className="relative isolate overflow-hidden pb-20 pt-24 sm:pt-36 lg:pb-28">
        <div className="hero-grid absolute inset-0 -z-10" /><div className="absolute -right-32 top-12 -z-10 h-[560px] w-[560px] rounded-full bg-blue-200/40 blur-3xl" />
        <div className="mx-auto grid max-w-[1440px] gap-12 px-5 sm:px-7 lg:grid-cols-[minmax(0,0.86fr)_minmax(520px,1.14fr)] lg:items-center lg:gap-8 lg:px-10">
          <div className="relative z-10"><p className="technical-label hero-enter text-blue-700">M.A.S. TRADERS / INDUSTRIAL SUPPLY</p><h1 className="hero-enter mt-5 max-w-2xl text-[clamp(3.5rem,7vw,7.5rem)] font-bold leading-[0.84] tracking-[-0.08em]">Built for<br/><span className="text-blue-600">the job.</span></h1><p className="hero-enter mt-7 max-w-md text-base leading-7 text-slate-600 sm:text-lg">Explore practical safety equipment, tools, fasteners, construction materials, and industrial supplies. Build a requirement and request a quote when ready.</p><div className="hero-enter mt-8 flex flex-wrap gap-3"><Link href="/catalogue" className="btn-primary">Explore Products <ArrowRight size={17}/></Link><a href={business.cataloguePdfUrl} download className="btn-secondary hero-download">Download Catalogue</a><button onClick={() => setQuoteOpen(true)} className="btn-secondary hero-request">Request a Quote</button></div><div className="hero-enter mt-8 flex flex-wrap gap-x-5 gap-y-3 border-t border-slate-200 pt-5 text-[0.66rem] font-bold uppercase tracking-[0.12em] text-slate-500 sm:mt-10 sm:gap-x-7 sm:text-xs"><span>Safety Equipment</span><span>Power Tools</span><span>Fasteners</span><span>Construction Materials</span></div></div>
          <div className="hero-enter hero-visual-panel relative min-h-[390px] sm:min-h-[520px] lg:min-h-[600px]"><div className="absolute inset-x-0 bottom-0 top-7 overflow-hidden rounded-[1.5rem] bg-white shadow-[0_28px_70px_rgba(15,23,42,0.12)] sm:rounded-[2rem]"><img src={heroImage} alt="Safety equipment, power tools, and fasteners from the M.A.S. Traders product range" className="h-full w-full object-cover object-center"/></div><div className="absolute left-0 top-0 grid h-20 w-20 place-items-center border border-slate-200 bg-[#f8fafc] font-mono text-xs font-bold text-blue-700 shadow-sm sm:h-24 sm:w-24">01 / 04</div><div className="hero-product-index absolute bottom-5 right-5 hidden max-w-[190px] rounded-2xl border border-white/40 bg-[#0b1220]/90 p-4 text-white shadow-xl backdrop-blur md:block md:bottom-6 md:right-6 md:max-w-[205px] md:p-5"><p className="technical-label text-blue-300">PRODUCT INDEX</p><p className="mt-2 text-sm font-semibold leading-5">Start with the product. Finish with a clearer quote request.</p></div></div>
        </div>
      </section>

      <section id="finder" className="border-y border-slate-200 bg-white py-16 sm:py-20"><div className="section-shell"><div className="section-rail">01 / FINDER</div><div><p className="technical-label text-blue-700">PRODUCT FINDER</p><div className="mt-3 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><h2 className="max-w-xl text-4xl font-bold leading-[0.95] tracking-[-0.06em] sm:text-5xl">What are you looking for?</h2><p className="max-w-sm text-sm leading-6 text-slate-600">Search the supplied catalogue by product name or category. Matching items appear immediately.</p></div><form onSubmit={submitFinder} className="relative mt-9 max-w-4xl"><Search className="absolute left-5 top-1/2 -translate-y-1/2 text-blue-700" size={20}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search products, tools, fasteners…" className="h-16 w-full rounded-2xl border border-slate-200 bg-[#f8fafc] pl-14 pr-40 text-base outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/><button className="absolute right-2 top-2 hidden h-12 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white hover:bg-blue-700 sm:inline-flex sm:items-center">Search catalogue</button></form>{matches.length ? <div className="mt-3 grid max-w-4xl divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white px-5 shadow-lg">{matches.map((product) => <div key={product.id} className="flex items-center justify-between gap-3 py-3"><Link href={`/product/${product.slug}`} className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{product.name}</p><p className="technical-label mt-1 text-blue-700">{product.category}</p></Link><button onClick={() => add(product)} className="shrink-0 rounded-lg p-2 text-blue-700 hover:bg-blue-50" aria-label={`Add ${product.name} to My Requirement`}><Plus size={17}/></button></div>)}</div> : null}</div></div></section>

      <section id="categories" className="py-20 sm:py-28"><div className="section-shell"><div className="section-rail">02 / CATEGORIES</div><MotionReveal><div><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="technical-label text-blue-700">CURATED INDEX</p><h2 className="mt-3 text-4xl font-bold leading-[0.96] tracking-[-0.06em] sm:text-5xl">Start where your work starts.</h2></div><Link href="/catalogue" className="link-arrow">View full catalogue <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{curated.map((item, index) => <Link key={item.category} href={`/catalogue?category=${encodeURIComponent(item.category)}`} className={`category-card group overflow-hidden bg-slate-100 ${index === 0 ? "md:col-span-2 xl:col-span-2" : ""}`}><img src={getCategoryCardImage(item.category)} alt={`${item.category} product range`} className="absolute inset-0 h-full w-full object-contain p-3 transition duration-500 group-hover:scale-[1.04] sm:p-4"/><div className="absolute inset-0 bg-gradient-to-t from-[#0b1220]/90 via-[#0b1220]/20 to-transparent"/><div className="category-card__content relative flex h-full min-h-[270px] flex-col justify-end p-6 text-white"><p className="technical-label text-blue-200">{String(index + 1).padStart(2, "0")} / {item.count} listed items</p><div className="mt-2 flex items-end justify-between gap-4"><h3 className="category-card__title max-w-[15rem] text-2xl font-bold leading-6 tracking-[-0.04em]">{item.category}</h3><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-600 transition group-hover:-translate-y-1 group-hover:translate-x-1"><ArrowDownRight size={18}/></span></div></div></Link>)}</div></div></MotionReveal></div></section>

      <section className="border-y border-slate-200 bg-white py-20 sm:py-28"><div className="section-shell"><div className="section-rail">03 / FEATURED</div><MotionReveal><div><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="technical-label text-blue-700">PRODUCT PREVIEW</p><h2 className="mt-3 text-4xl font-bold leading-[0.96] tracking-[-0.06em] sm:text-5xl">A working selection.</h2></div><p className="max-w-xs text-sm leading-6 text-slate-600">Product names are drawn directly from the supplied catalogue. Details not provided are intentionally omitted.</p></div><div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-8 sm:gap-x-5 sm:gap-y-10 xl:grid-cols-3">{featured.map((product) => <ProductCard key={product.id} product={product}/>)}</div></div></MotionReveal></div></section>

      <section className="bg-[#0b1220] py-20 text-white sm:py-28"><div className="section-shell"><div className="section-rail text-blue-300">04 / CATALOGUE</div><div className="grid gap-10 lg:grid-cols-[1fr_0.78fr] lg:items-end"><div><p className="technical-label text-blue-300">FULL PRODUCT INDEX</p><h2 className="mt-4 max-w-2xl text-5xl font-bold leading-[0.9] tracking-[-0.065em] sm:text-6xl">The full catalogue, grouped by work.</h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-300">Browse the supplied product index across safety, tools, fasteners, construction materials, and specialist product groups.</p><div className="mt-8"><Link href="/catalogue" className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-blue-500">Explore full catalogue <ArrowRight className="ml-2 inline" size={16}/></Link></div></div><div className="border border-white/15 bg-white/[0.04] p-6 backdrop-blur-sm"><div className="flex items-center gap-3"><ClipboardList className="text-blue-300"/><p className="technical-label text-slate-300">CATEGORY INDEX</p></div><div className="mt-6 space-y-3">{categories.slice(0, 5).map((category, index) => <div key={category.category} className="flex items-center justify-between border-b border-white/10 pb-3 text-sm"><span><span className="mr-3 font-mono text-blue-300">{String(index + 1).padStart(2, "0")}</span>{category.category}</span><strong className="font-mono text-slate-300">{category.count}</strong></div>)}</div><Link href="/catalogue" className="mt-7 inline-flex text-xs font-bold uppercase tracking-[0.12em] text-blue-300 hover:text-white">View all categories <ArrowRight className="ml-2" size={14}/></Link></div></div></div></section>

      <section className="py-20 sm:py-28"><div className="section-shell"><div className="section-rail">05 / ASSIST</div><MotionReveal><div><p className="technical-label text-blue-700">NOT SURE WHAT YOU NEED?</p><h2 className="mt-3 max-w-2xl text-4xl font-bold leading-[0.96] tracking-[-0.06em] sm:text-5xl">Bring the material list. We’ll keep the request clear.</h2><div className="mt-10 grid gap-4 md:grid-cols-3"><AssistCard icon={<Upload size={21}/>} title="Send a photo" text="Attach a product or reference photo to the quote request." onClick={() => setQuoteOpen(true)} /><AssistCard icon={<FileText size={21}/>} title="Send a list" text="Attach a material or product list when you submit your requirement." onClick={() => setQuoteOpen(true)} /><AssistCard icon={<Wrench size={21}/>} title="Describe it" text="Add practical notes to the products in your working requirement." onClick={() => setOpen(true)} /></div></div></MotionReveal></div></section>

      <section className="border-y border-slate-200 bg-[#eef5ff] py-20 sm:py-28"><div className="section-shell"><div className="section-rail">06 / REQUIREMENT</div><div className="grid gap-10 lg:grid-cols-[1fr_0.78fr] lg:items-end"><div><p className="technical-label text-blue-700">MY REQUIREMENT</p><h2 className="mt-4 max-w-2xl text-5xl font-bold leading-[0.9] tracking-[-0.065em] sm:text-6xl">Turn a product list into a clear request.</h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-600">Keep products, quantities, and notes together while you browse. When the list is ready, send the requirement for quotation.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => setOpen(true)} className="btn-primary">Open My Requirement <span className="rounded-md bg-white/15 px-1.5 py-0.5 text-xs">{items.length}</span></button><button onClick={() => setQuoteOpen(true)} className="btn-secondary">Request a Quote</button></div></div><div className="rounded-2xl border border-blue-200 bg-white p-6 shadow-[0_18px_50px_rgba(11,99,246,0.11)]"><div className="flex items-center gap-3"><ClipboardList className="text-blue-700"/><p className="technical-label text-slate-500">WORKING LIST</p></div><div className="mt-6 space-y-3">{items.length ? items.slice(0, 3).map((item) => <div key={item.id} className="flex items-center justify-between border-b border-slate-100 pb-3 text-sm"><span>{item.name}</span><strong className="font-mono text-blue-700">×{item.quantity}</strong></div>) : <p className="text-sm leading-6 text-slate-500">Your selection will appear here as you add products from the catalogue.</p>}</div><div className="mt-7 flex items-center justify-between text-xs font-bold uppercase tracking-[0.12em] text-slate-500"><span>{items.length} item{items.length === 1 ? "" : "s"}</span><button onClick={() => setOpen(true)} className="text-blue-700 hover:text-blue-900">Review list</button></div></div></div></div></section>

      <section className="py-20 sm:py-28"><div className="section-shell"><div className="section-rail">07 / TRUST</div><div><p className="technical-label text-blue-700">PRACTICAL PROCESS</p><h2 className="mt-3 max-w-2xl text-4xl font-bold leading-[0.96] tracking-[-0.06em] sm:text-5xl">A straightforward product-to-requirement workflow.</h2><div className="mt-10 grid gap-4 sm:grid-cols-3"><TrustFact text="Browse supplied product categories"/><TrustFact text="Build quantities and notes"/><TrustFact text="Attach material references"/></div></div></div></section>

      <section id="about" className="border-y border-slate-200 bg-white py-20 sm:py-28"><div className="section-shell"><div className="section-rail">08 / ABOUT</div><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="technical-label text-blue-700">M.A.S. TRADERS</p><img src={logoUrl} alt="M.A.S. Traders" className="mt-5 h-24 w-36 object-contain object-left"/></div><div><h2 className="text-4xl font-bold leading-[0.98] tracking-[-0.06em] sm:text-5xl">An industrial product catalogue built around a more practical next step.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-slate-600">M.A.S. Traders is presented here as a catalogue and requirement-building experience for industrial products in Kovilpatti, Tamil Nadu. This site intentionally avoids unsupported claims and displays only the product catalogue information supplied for the build.</p></div></div></div></section>

      <section id="contact" className="border-b border-slate-200 bg-white py-16 sm:py-20"><div className="section-shell"><div className="section-rail">09 / CONTACT</div><div className="grid gap-8 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><p className="technical-label text-blue-700">VERIFIED LOCATION</p><h2 className="mt-3 text-4xl font-bold leading-[0.96] tracking-[-0.06em] sm:text-5xl">Kovilpatti,<br/>Tamil Nadu.</h2><p className="mt-4 text-sm font-semibold text-slate-600">{business.locality}</p></div><div className="grid gap-3 sm:grid-cols-2"><a href={business.phoneHref} className="rounded-xl border border-slate-200 bg-[#f8fafc] p-5 transition hover:border-blue-300"><p className="technical-label text-blue-700">PHONE</p><p className="mt-2 font-bold text-slate-950">{business.phoneDisplay}</p></a><a href={business.emailHref} className="rounded-xl border border-slate-200 bg-[#f8fafc] p-5 transition hover:border-blue-300"><p className="technical-label text-blue-700">EMAIL</p><p className="mt-2 break-all font-bold text-slate-950">{business.email}</p></a></div></div></div></section>

      <section className="border-y border-slate-200 bg-white py-20 sm:py-24"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 px-5 sm:px-7 lg:flex-row lg:items-end lg:justify-between lg:px-10"><div className="border-l-2 border-blue-600 pl-5"><p className="technical-label text-blue-700">NEXT STEP / REQUEST QUOTE</p><h2 className="mt-4 max-w-2xl text-5xl font-bold leading-[0.9] tracking-[-0.065em] sm:text-6xl">Your requirement, ready when you are.</h2></div><button onClick={() => setQuoteOpen(true)} className="btn-primary self-start lg:self-auto">Request a Quote <ArrowRight size={17}/></button></div></section>
    </main>
    <footer className="bg-[#0b1220] px-5 py-12 text-white sm:px-7 lg:px-10">
      <div className="mx-auto flex max-w-[1440px] flex-col gap-8 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <img src={logoUrl} alt="M.A.S. Traders" className="h-16 w-16 object-cover rounded-full shadow-sm" />
          <p className="mt-5 max-w-sm text-sm leading-6 text-slate-400">Industrial product catalogue and requirement builder for M.A.S. Traders, {business.locality}.</p></div><div className="grid grid-cols-2 gap-x-8 gap-y-3 text-sm font-semibold text-slate-300"><Link href="/catalogue" className="hover:text-white">Products</Link><button onClick={() => setOpen(true)} className="text-left hover:text-white">My Requirement</button><a href="#categories" className="hover:text-white">Categories</a><a href={business.cataloguePdfUrl} download className="hover:text-white">Download catalogue</a><a href={business.phoneHref} className="hover:text-white">Call</a><button onClick={() => setQuoteOpen(true)} className="text-left hover:text-white">Request a Quote</button></div></div><div className="mx-auto mt-10 flex max-w-[1440px] items-center justify-between border-t border-white/10 pt-5 text-xs text-slate-500"><span>© {new Date().getFullYear()} M.A.S. Traders</span><span>{business.locality}</span></div></footer>
    <MobileActionBar />
  </div>;
}

function AssistCard({ icon, title, text, onClick }: { icon: React.ReactNode; title: string; text: string; onClick: () => void }) { return <button onClick={onClick} className="motion-card group min-h-44 rounded-2xl border border-slate-200 bg-white p-6 text-left shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700 transition group-hover:bg-blue-600 group-hover:text-white">{icon}</span><h3 className="mt-6 text-xl font-bold tracking-[-0.04em]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Choose this path <ArrowRight size={15}/></span></button>; }
function TrustFact({ text }: { text: string }) { return <div className="flex items-center gap-3 border-b border-slate-200 py-3 text-sm font-semibold text-slate-700"><CheckCircle2 size={17} className="text-blue-700"/>{text}</div>; }
