import { ArrowLeft, ArrowRight, Check, Plus } from "lucide-react";
import { Link, useRoute } from "wouter";
import SiteHeader from "@/components/SiteHeader";
import ProductCard from "@/components/ProductCard";
import { currentProducts, getProduct, productImage } from "@/lib/catalogue";
import { useRequirement } from "@/components/RequirementProvider";
import { MobileProductActionBar } from "@/components/MobileActionBar";
import { MotionReveal } from "@/components/Motion";

export default function ProductDetail() {
  const [, params] = useRoute("/product/:slug");
  const product = getProduct(params?.slug ?? "");
  const { add, setQuoteOpen } = useRequirement();
  if (!product) return <div className="min-h-screen bg-[#f8fafc]"><SiteHeader/><main className="grid min-h-[70vh] place-items-center pt-20"><div className="text-center"><p className="technical-label text-blue-700">PRODUCT NOT FOUND</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.05em]">That product is not in this index.</h1><Link href="/catalogue" className="mt-6 inline-flex text-sm font-bold text-blue-700">Back to catalogue</Link></div></main></div>;
  const related = currentProducts.filter((item) => item.category === product.category && item.id !== product.id).slice(0, 3);
  return <div className="min-h-screen bg-[#f8fafc] pb-24 text-slate-950 lg:pb-0"><SiteHeader/><main className="pt-24 sm:pt-28"><MotionReveal className="mx-auto max-w-[1440px] px-5 sm:px-7 lg:px-10"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><Link href="/catalogue" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-slate-600 transition hover:text-blue-700"><ArrowLeft size={16}/> Back to catalogue</Link><p className="technical-label text-blue-700">10 / PRODUCT RECORD</p></div><div className="mt-6 grid gap-8 lg:mt-8 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,0.85fr)] lg:items-center lg:gap-10"><div className="product-detail-image relative aspect-[1.08/1] overflow-hidden rounded-[1.5rem] bg-white sm:rounded-[2rem]"><img src={productImage(product)} alt={product.name} width={1200} height={1200} className="h-full w-full object-contain p-5 sm:p-8"/><span className="media-corner"/><span className="absolute bottom-4 left-4 border-l-2 border-blue-600 bg-white/90 px-3 py-2 font-mono text-[0.65rem] font-bold text-slate-700 sm:bottom-5 sm:left-5 sm:text-xs">CAT / {product.category.toUpperCase()}</span></div><div><p className="technical-label text-blue-700">{product.category}</p><h1 className="mt-3 text-[clamp(2.6rem,12vw,3.6rem)] font-bold leading-[0.97] tracking-[-0.065em] sm:text-6xl">{product.name}</h1><div className="mt-6 border-l-2 border-blue-600 pl-4 text-sm leading-6 text-slate-600 sm:mt-7">This listing is sourced from the supplied M.A.S. Traders catalogue. No additional specifications, price, brand, model, or availability details have been published here.</div><div className="mt-8 grid gap-3 sm:grid-cols-2"><button onClick={() => add(product)} className="btn-primary justify-center"><Plus size={17}/> Add to Requirement</button><button onClick={() => setQuoteOpen(true)} className="btn-secondary justify-center">Request a Quote <ArrowRight size={17}/></button></div><div className="mt-8 flex items-center gap-2 text-sm text-slate-600"><Check size={16} className="text-blue-700"/> Added items stay in My Requirement while you browse.</div></div></div></MotionReveal>
    {related.length ? <MotionReveal className="mx-auto mt-20 max-w-[1440px] px-5 pb-8 sm:mt-24 sm:px-7 lg:px-10"><section><div className="mb-8 flex items-end justify-between"><div><p className="technical-label text-blue-700">11 / SAME CATEGORY</p><h2 className="mt-2 text-3xl font-bold tracking-[-0.05em]">Continue browsing</h2></div><Link href="/catalogue" className="hidden text-sm font-bold text-blue-700 sm:inline-flex">View catalogue <ArrowRight className="ml-2" size={16}/></Link></div><div className="grid grid-cols-2 gap-x-4 gap-y-8 sm:gap-x-5 sm:gap-y-10 lg:grid-cols-3">{related.map((item, index) => <ProductCard key={item.id} product={item} index={index}/>)}</div></section></MotionReveal> : null}
  </main><MobileProductActionBar onAdd={() => add(product)} onQuote={() => setQuoteOpen(true)} /></div>;
}
